import { CI_RESULT_ARTIFACT_NAME, CI_RESULT_FILE_NAME, CI_RUNNER_PATH } from '@devdigest/shared';
import type { AllowedTriggerType } from './constants.js';

/**
 * The generated GitHub Actions workflow.
 *
 * **A template string, not `yaml.stringify`, and that is the requirement rather
 * than a shortcut.** This file is committed into a repository DevDigest does not
 * maintain, and somebody there has to review it before merging: the
 * `permissions:` block, the trigger set, the fork gate and the one secret
 * reference are the whole security case for the feature, and they have to be
 * legible in the file itself. `stringify` would drop every comment and reorder
 * nothing predictably. The manifest is the opposite case — see `manifest.ts`.
 *
 * Four things this template guarantees, each with a test that fails if it moves:
 *
 *  - `permissions:` declares exactly `contents: read` and `pull-requests: write`.
 *    Everything unlisted is `none` by GitHub's own rule, so this is a complete
 *    statement of what the workflow token can do.
 *  - The only trigger is `pull_request`. The strings `pull_request_target`,
 *    `issue_comment` and `pull_request_review_comment` appear nowhere — not in a
 *    comment either, because a substring search is what checks it.
 *  - The job carries a fork gate as an `if:` on the JOB, so a pull request from
 *    a fork runs nothing at all. Deliberately in the YAML rather than inside the
 *    runner: a previous implementation of this feature promised the same thing in
 *    a header comment and nothing implemented it, and a comment is not a control.
 *  - Every `uses:` is a first-party `actions/…` at a major-version tag, and the
 *    review step is a `run:` of the exported runner. There is no third-party
 *    action in reach of the key, which is what makes tags rather than commit pins
 *    the right choice here: this file lands in repositories nobody will come back
 *    to re-pin.
 *
 * `actions/setup-node` is load-bearing. The review step runs `node` directly
 * rather than invoking a node20 action that would carry its own runtime, so
 * without it the Node version is whatever `ubuntu-latest` happens to ship that
 * month.
 *
 * **`post_as` travels as a CLI FLAG, not an environment variable**, because that
 * is the interface the runner accepts. This is the one interpolation in the file
 * with no hermetic test that could catch a mismatch: the runner defaults the flag
 * to `github_review` when it is absent, so a generator that emitted the mode
 * anywhere else would leave every unit test on both sides green while
 * `post_as: none` posted a review in a real repository.
 */

export interface WorkflowInput {
  /** Slug of the agent whose manifest the runner is pointed at. */
  agentSlug: string;
  /** Already intersected with the supported set — see `resolveTriggerTypes`. */
  triggerTypes: readonly AllowedTriggerType[];
  /** Where the runner publishes its verdict. */
  postAs: 'github_review' | 'pr_comment' | 'none';
}

export function buildWorkflow(input: WorkflowInput): string {
  const { agentSlug, triggerTypes, postAs } = input;
  const types = triggerTypes.join(', ');

  return `# Generated by DevDigest. Re-exporting the agent overwrites this file.
#
# What this workflow may do, in full:
#   - read this repository's contents, and write pull request reviews;
#   - run only on pull requests raised from a branch of THIS repository, never
#     from a fork, so the model key is never exposed to a contributor's branch;
#   - execute the reviewer committed alongside it at ${CI_RUNNER_PATH}, and three
#     first-party actions/ steps. Nothing else runs beside the key.
name: DevDigest Review

on:
  pull_request:
    types: [${types}]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    # Fork gate. A pull request whose head repository is not this one runs NO
    # job, so no step and no secret is reachable from a contributor's branch.
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # The reviewer itself: a single self-contained file committed by the
      # export. It reads the diff from the GitHub API and clones nothing.
      #
      # All three env entries are load-bearing. The runner checks its environment
      # and exits naming what is missing BEFORE it does any work: the model key it
      # cannot review without, the repository token it reads the diff and posts
      # with — which Actions does NOT put in the environment by itself — and the
      # repository name, which the host sets but which is mapped here so the step
      # does not depend on inheriting it.
      - name: DevDigest review
        run: node ${CI_RUNNER_PATH} review --agent ${agentSlug} --post-as ${postAs}
        env:
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: \${{ github.repository }}

      # if: always() — a run that trips the gate exits non-zero, and its result
      # is exactly the one somebody wants to read. The artifact name is a
      # contract with the studio's reader; it is not free to change here.
      - name: Upload DevDigest result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${CI_RESULT_ARTIFACT_NAME}
          path: ${CI_RESULT_FILE_NAME}
          if-no-files-found: ignore
`;
}
