import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';

/**
 * server — `@devdigest/api`.
 *
 * Two jobs beyond catching typos:
 *
 * 1. **Promise hygiene.** `no-floating-promises` / `no-misused-promises` need type
 *    information, so this config uses `projectService`. It is the class of bug
 *    `tsc` cannot see and this codebase is full of awaited chains and background
 *    jobs (`platform/jobs.ts`).
 * 2. **Style rules `tsc` does not cover** — unused vars, `no-explicit-any`.
 *
 * It deliberately does NOT police the onion boundaries: `.dependency-cruiser.cjs`
 * already owns those as a ratchet (`pnpm arch`). One law, one enforcer — two would
 * drift apart, and the graph rules there see things a per-file linter cannot.
 */
export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      // Cloned third-party repos live here (git clone target) — never ours to lint.
      'clones/**',
      // Generated by drizzle-kit.
      'src/db/migrations/**',
      // CommonJS config outside the TS project; its own rules live in the file.
      '.dependency-cruiser.cjs',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      globals: { ...globals.node },
      parserOptions: {
        // tsconfig.eslint.json, not tsconfig.json: the build's include is src/**
        // only, so test/** and this file would not parse under the type-aware rules.
        project: ['./tsconfig.eslint.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // OFF, deliberately: every mock and adapter implements an async PORT
      // interface, so the method must be `async` whether or not its body awaits
      // anything (`adapters/mocks.ts` alone would raise ~25 of these).
      '@typescript-eslint/require-await': 'off',
      // Real but cosmetic — a handful in the adapters. Warn so the count is
      // visible without blocking CI on a redundant `as`.
      '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
      // Unused args are a real signal in handlers; `_`-prefixed ones are intentional.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // A dropped promise here means a silently unfinished DB write or job.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      // The codebase has zero `any` today (measured) — keep it that way.
      '@typescript-eslint/no-explicit-any': 'error',
      // Boundary casts are onion law 7's failure mode; too noisy to ban outright,
      // so surface them as warnings rather than silence them.
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-unsafe-return': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
    },
  },

  // Vendored cross-package contract — coordination-only, not ours to lint.
  { files: ['src/vendor/**'], rules: { '@typescript-eslint/no-explicit-any': 'off' } },

  // Tests reach into internals on purpose, and assert on loosely-typed payloads.
  {
    files: ['test/**'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  // Config files are not part of the TS project.
  {
    files: ['*.js', '*.mjs', '*.config.ts'],
    ...tseslint.configs.disableTypeChecked,
  },
);
